INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P1', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P2', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P3', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P4', '1Q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P5', '1Q');